packages:
  - name: reddit
    actions:
      - name: hot
        runtime: 'python:default'
        environment:
          REDDIT_CLIENT_ID: "${REDDIT_CLIENT_ID}"
          REDDIT_CLIENT_SECRET: "${REDDIT_CLIENT_SECRET}"
